name: Release

on:
  push:
    tags:
      - "*"

jobs:
  tests:
    runs-on: macos-12
    steps:
      - uses: ./.github/actions/run-tests
  release:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
