name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: macos-12
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Legacy architecture
            scheme: TvOSExample
            pod_install_command: bundle exec pod install
          - name: Fabric architecture
            scheme: FabricTvOSExample
            pod_install_command: RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "${{ matrix.scheme }}/pnpm-lock.yaml"
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          working-directory: ${{ matrix.scheme }}/ios
      - name: Install node dependencies
        working-directory: ${{ matrix.scheme }}
        run: pnpm install
      - name: Install pods
        working-directory: ${{ matrix.scheme }}/ios
        run: ${{ matrix.pod_install_command }}
      - name: Build app
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          workspace: ${{ matrix.scheme }}/ios/${{ matrix.scheme }}.xcworkspace
          scheme: ${{ matrix.scheme }}-tvOS
          destination: platform=TvOS Simulator,name=Apple TV
          action: clean build
          build-settings: CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
