name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  run-tests:
    runs-on: macos-12
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Legacy architecture
            scheme: TvOSExample
            pod_install_command: pod install
          - name: Fabric architecture
            scheme: FabricTvOSExample
            pod_install_command: RCT_NEW_ARCH_ENABLED=1 pod install
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "${{ matrix.scheme }}/yarn.lock"
      - name: Install node dependencies
        working-directory: ${{ matrix.scheme }}
        run: yarn
      - name: Install pods
        working-directory: ${{ matrix.scheme }}/ios
        run: ${{ matrix.pod_install_command }}
      - name: Build app
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          workspace: ${{ matrix.scheme }}/ios/${{ matrix.scheme }}.xcworkspace
          scheme: ${{ matrix.scheme }}-tvOS
          destination: platform=TvOS Simulator,name=Apple TV
          action: clean build
          build-settings: CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  release:
    needs: run-tests
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
